export const VERIFY_ACCESS_REQUEST = 'VERIFY_ACCESS_REQUEST';
export const SET_IS_VALID_TOKEN = 'SET_IS_VALID_TOKEN';
export const SET_ACCESS_TOKEN = 'SET_ACCESS_TOKEN';
export const SET_USER_ID = 'SET_USER_ID';
