export const GET_USERS_REQUEST = 'common/GET_USERS_REQUEST';
export const SET_USERS_DATA = 'common/SET_USERS_DATA';

export const SET_SETTINGS_MODAL_STATE = 'common/SET_SETTINGS_MODAL_STATE';
export const GET_CURRENT_USER_PROFILE_REQUEST = 'common/GET_CURRENT_USER_PROFILE_REQUEST';
export const SET_CURRENT_USER_PROFILE = 'common/SET_CURRENT_USER_PROFILE';
export const REMOVE_BANK_CARD_REQUEST = 'common/REMOVE_BANK_CARD_REQUEST';
export const SET_USER_UPDATE_SUCCESS_MSG = 'common/SET_USER_UPDATE_SUCCESS_MSG';
export const SET_CARD_ADDING_ERROR_MSG = 'common/SET_CARD_ADDING_ERROR_MSG';
