export const GET_USERS_REQUEST = 'common/GET_USERS_REQUEST';
export const SET_USERS_DATA = 'common/SET_USERS_DATA';

export const SET_SETTINGS_MODAL_STATE = 'common/SET_SETTINGS_MODAL_STATE';
export const GET_CURRENT_USER_PROFILE_REQUEST = 'common/GET_CURRENT_USER_PROFILE_REQUEST';
export const SET_CURRENT_USER_PROFILE = 'common/SET_CURRENT_USER_PROFILE';
