export const FETCH_STORES_REQUEST = 'store/FETCH_STORES_REQUEST';
export const FETCH_STORES_SUCCESS = 'store/FETCH_STORES_SUCCESS';

export const FETCH_STORE_CONTENT_REQUEST = 'store/FETCH_STORE_CONTENT_REQUEST';
export const FETCH_STORE_CONTENT_SUCCESS = 'store/FETCH_STORE_CONTENT_SUCCESS';

export const FETCH_CATEGORIES_REQUEST = 'store/FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'store/FETCH_CATEGORIES_SUCCESS';

export const FETCH_ITEMS_REQUEST = 'store/FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'store/FETCH_ITEMS_SUCCESS';

export const CREATE_STORE_ORDER_REQUEST = 'store/CREATE_STORE_ORDER_REQUEST';

export const UPDATE_STORE_ORDER_REQUEST = 'store/UPDATE_STORE_ORDER_REQUEST';
export const UPDATE_STORE_ORDER_SUCCESS = 'store/UPDATE_STORE_ORDER_SUCCESS';

export const SUBMIT_STORE_ORDER_REQUEST = 'store/SUBMIT_STORE_ORDER_REQUEST';
export const SUBMIT_STORE_ORDER_SUCCESS = 'store/SUBMIT_STORE_ORDER_SUCCESS';

export const UPDATE_CHOOSED_ITEMS = 'store/UPDATE_CHOOSED_ITEMS';
export const SET_ORDER_JUST_SUBMITTED_STATE = 'store/SET_ORDER_JUST_SUBMITTED_STATE';
