export const FETCH_STORES_REQUEST = 'store/FETCH_STORES_REQUEST';
export const FETCH_STORES_SUCCESS = 'store/FETCH_STORES_SUCCESS';

export const FETCH_CATEGORIES_REQUEST = 'store/FETCH_CATEGORIES_REQUEST';
export const FETCH_CATEGORIES_SUCCESS = 'store/FETCH_CATEGORIES_SUCCESS';

export const FETCH_ITEMS_REQUEST = 'store/FETCH_ITEMS_REQUEST';
export const FETCH_ITEMS_SUCCESS = 'store/FETCH_ITEMS_SUCCESS';

export const CREATE_STORE_ORDER_REQUEST = 'store/CREATE_STORE_ORDER_REQUEST';
